### ISSUE TITLE
질문. nodejs와 spring

### ISSUE THREAD

**Issue by tae0code** [TeamCrazyPerformance/LazyPeoplesProject#1]
nodejs와 spring을 간략하게 설명해주실분을 구합니다.

성능적인 측면과 확장성에 대해 궁금합니다.
-->성능적인 측면이라 함은 수학적 계산, 반응성, 트래픽처리..등등..

**Comment by creaton60** [comment]
@net9keep 
질문이 잘 이해가 안갑니다.
nodejs 와 spring 은 둘다 서버 프레임워크 입니다.
말씀하신 수학적 계산, 반응성 트래픽 처리는
프레임워크가 아니라 아키텍처와 네트워크 모델링, 데이터 로직에 관한 얘기입니다.

즉 nodejs 를 쓰시든 spring 을 쓰시든 문의 해주신
성능적인 측면은 비교가 불가능합니다. 둘다 편히쓰기 위해 만들어진 프레임워크니까요

확장성도 nodejs 와 spring 둘다 좋습니다.
둘다 프레임워크니까요...

한번 생각해보시고 피드백 부탁드릴게요

**Comment by tae0code** [comment]
음.. 제가 잘못생각하고 있었네요.
저는 back-end 쪽에서 사용자가 요청한 계산을 처리하고싶었는데 속도 차이가 나는지 궁금했습니다.
멍청하기 짝이 없었군요.
