### ISSUE TITLE
javascript 비트연산과 논리연산 &

### ISSUE THREAD

**Issue by joi0104** [TeamCrazyPerformance/LazyPeoplesProject#7]
js공부하다가 비트연산과 논리연산에 대해 혼란이 와서 이슈를 올려요.

```
if (true&true){
    console.log("running");
}
```

위 코드처럼 작성하면 &연산자가 논리연산자로 작동이 되서 true값을 반환하고 if문이 실행됩니다.

```
if (2&1){
    console.log("running");
}
```
하지만 위 코드처럼 작성하면 &연산자가 비트연산자로 작동이 되서 0값을 반환하고 if문이 실행되지 않습니다.

보통 short-circit을 따르는 &&연산자를 논리연산자로 사용하지만, &연산자도 논리연산자로 작동이 되는것을 알고 이런저런 코드를 작성하다가 혼란이 오더라구요.

&연산자를 사용하는 경우에 비트연산을 하는 경우도 있고 논리연산을 하는 경우도 있던데 어떤 경우에 비트연산을 하고, 어떤 경우에 논리연산을 하는지 궁금합니다.

**Comment by hyesun03** [comment]
일단 javascript에는 [truthy](https://developer.mozilla.org/ko/docs/Glossary/Truthy)한 값과, [falsy](https://developer.mozilla.org/ko/docs/Glossary/Falsy)한 값이 있습니다.

truthy와 falsy가 뭘 의미하는지는 쪼금만 찾아보면 금방 받아들일것 같으니, 아래 코드가 왜 동작을 안하는지 설명을 할게요.

``` javascript
if (2&1){
    console.log("running");
}
```
결론부터 말하자면, & 연산자가 가끔 [논리연산자](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/%EB%85%BC%EB%A6%AC_%EC%97%B0%EC%82%B0%EC%9E%90(Logical_Operators))로 작동을 하는게 아니라, &는 그냥 [비트연산자](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators)가 맞습니다. if 내의 조건식은 참/거짓만 판단을 하면 되기 때문에, truthy하게 혹은 falsy하게 취급이 되는 것 뿐이죠.

설명을 하기 위해서, 1에서 8까지의 숫자를 2진수로 표현해보면 아래와 같습니다.
```
1 = 0001
2 = 0010
3 = 0011
4 = 0100
5 = 0101
6 = 0110
7 = 0111
8 = 1000
```

아래를 보면 1&2는 0이고, **0은 falsy한 값이어서** if내의 `console.log("running")`이 실행되지 않는 것입니다.
```
  0001
& 0010
-----------
= 0000
```

---

이와 마찬가지로, `3&4 = 0`, `1&8 = 0` 이기 때문에 if내의 `console.log()`가 찍히질 않습니다.
``` javascript
if (3&4){
    console.log("running");
}

if (1&8){
    console.log("running");
}
```

**0 이외의 숫자값들은 truthy한 값으로 취급**되는데요, 그렇기 때문에 아래에서는  if내의 `console.log()`가 찍힙니다.
``` javascript
if (2&3){
    console.log("running");
}

if (4&6){
    console.log("running");
}
```

**Comment by joi0104** [comment]
& 연산자가 비트연산자로 작동을 한다면
```
if (true&true){
    console.log("running");
}
```
위의 코드에서는 true값이 1로 변환이 되어 비트연산이 실행되는 건가요?

또 그렇다면 1과 1의 비트연산 결과값인 1이 truthy한 값으로 인식되어서 제어문이 실행되는 건가요?

**Comment by hyesun03** [comment]
``` javascript
if (true&true){
    console.log("running");
}
```
위의 코드에서는 true값이 1로 변환이 되어 비트연산이 실행되는 건가요?
-> 네. 비트연산자는 연산을 하기 위해서 피연산자가 32비트 정수형으로 암묵적인 형변환이 이뤄지는데, 이 때 true가 1로 바뀝니다. 마찬가지로, false는 0으로 변환이 됩니다. 

``` javascript
// true & 2 -> 1 & 2 -> 0 -> falsy 값 -> if 블록 실행 X
if(true & 2) {
    console.log("run");
}

// true & 3 -> 1 & 3 -> 1 -> truthy 값 -> if 블록 실행 O
if(true & 3) {
    console.log("run");
}

// false | 5 -> 0 | 5 -> 5 -> truthy 값 -> if 블록 실행 O
if(false | 5) {
    console.log("run");
}
```

또 그렇다면 1과 1의 비트연산 결과값인 1이 truthy한 값으로 인식되어서 제어문이 실행되는 건가요?
-> 네

---
첨언하자면 JavaScript 뿐만이 아니라, Python에서도 `True & 숫자`이런식으로 해당 숫자의 끝 비트가 0인지 1인지를 판단 할 때 쓸 수 있습니다 ㅎㅎ

**Comment by joi0104** [comment]
확실하게 이해가 되었어요! 감사합니다
